version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: virgool-backend-clone
    restart: always
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: >
      sh -c "
      until pg_isready -h db -p 5432 -U ${DB_USERNAME}; do echo 'Waiting for database...'; sleep 2; done;
      npm run migration:run &&
      npm run start:prod"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: virgool-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DB_USERNAME}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
